# Generated by Django 4.1.7 on 2023-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(default=None, upload_to='image/'),
        ),
    ]
