# Generated by Django 4.1.7 on 2023-03-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofilemodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='User',
        ),
    ]
